import type { Metadata } from 'next';
import './globals.scss';
import 'dotenv/config';
import ClientProvider from './ClientProvider';
import '@backstabbersgame/design-system/styles/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <head></head>
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
